# Runs randomized_msgq twice with the same +randomized_seed and fails unless
# the per-PE run-order digests of the two runs are identical.
set(args random +pe 2 +randomized_msgq +randomized_seed 12345)
set(digests)
foreach(run 1 2)
  execute_process(COMMAND ${PROG} ${args}
                  RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "run ${run} failed (rc=${rc}):\n${out}\n${err}")
  endif()
  string(REGEX MATCHALL "\\[[0-9]+\\] run order digest [0-9a-f]+" lines "${out}")
  list(SORT lines)
  list(LENGTH lines n)
  if(n LESS 2)
    message(FATAL_ERROR "run ${run}: expected a digest line per PE, got ${n}:\n${out}")
  endif()
  string(REPLACE ";" " | " joined "${lines}")
  list(APPEND digests "${joined}")
endforeach()
list(GET digests 0 a)
list(GET digests 1 b)
if(NOT a STREQUAL b)
  message(FATAL_ERROR "digests differ between runs:\n${a}\n${b}")
endif()
message(STATUS "digests identical across two seeded runs: ${a}")
