name: LCI1

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build libfabric-bin libfabric-dev openmpi-bin openmpi-common openmpi-doc libopenmpi-dev

      - name: Verify Installation
        run: |
          cmake --version
          ninja --version
          mpicc --version
          mpirun --version
          fi_info --version

      - name: Configure
        shell: bash
        run: |
            cmake \
                -Bbuild \
                -GNinja \
                -DCMAKE_BUILD_TYPE=Debug \
                -DRECONVERSE_TRY_ENABLE_COMM_LCI1=ON \
                -DRECONVERSE_AUTOFETCH_LCI1=ON \
                -DLCI_SERVER=ofi \
                -DLCT_PMI_BACKEND_ENABLE_MPI=ON \
                .

      - name: Build
        shell: bash
        run: |
            cmake --build build --target all

      - name: Test
        shell: bash
        run: |
            cd build
            ctest --extra-verbose --timeout 60
