name: Clang-Format Check

on:
  pull_request:
    paths:
      - '**/*.cpp'
      - '**/*.h'
      - '**/*.c'
      - '**/*.hpp'

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up clang-format
      run: |
        sudo apt-get update
        sudo apt-get install clang-format

    - name: Verify clang-format installation
      run: |
        clang-format --version

    - name: Run clang-format on all files
      run: |
        # From anywhere inside the repo:
        repo_root=$(git rev-parse --show-toplevel) && cd "$repo_root"
        git ls-files -z -- '*.c' '*.cc' '*.cpp' '*.cxx' '*.h' '*.hh' '*.hpp' '*.hxx' \
        | xargs -0 -r clang-format -i

        # Fail if formatting made changes
        git diff --exit-code || {
          echo "clang-format changed files above. Please commit the formatting."
          exit 1
        }